services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: loginservice-app
    ports:
      - "8082:8082"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-container:3306/ms_db_1
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      MYSQL_HOST: mysql-container
      MYSQL_PORT: 3306
      MYSQL_DATABASE: ms_db_1
      MYSQL_USER: root
      MYSQL_PASSWORD: root

  mysql:
    image: mysql:8.0
    container_name: mysql-container
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ms_db_1
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
